// Shared shapes for the Golden Goose Machine flow. Mirrors the
// golden_goose_submissions table columns (see the migration in
// app/api/golden-goose routes) so API responses and the DB row line up 1:1.

export interface SiteAnalysis {
  companySummary: string;
  services: string[];
  industries: string[];
  residentialCommercial: 'residential' | 'commercial' | 'both';
  customerTypes: string[];
  specialties: string[];
}

// Same shape as SiteAnalysis but arrays are pre-filtered to only the items
// the user left checked on the verification screen.
export type VerifiedAttributes = SiteAnalysis;

export interface RoleClarificationTurn {
  question: string;
  answer: string;
}

export interface RoleClarificationResult {
  sufficient: boolean;
  followUpQuestion?: string;
}

// One row of the 3-column Golden Goose table. topFiveToMeet must always
// have exactly 5 entries — enforced by validation in generate-report,
// not left to the model's discretion.
export interface GoldenGooseRow {
  name: string;
  whatTheyCanDo: string;
  topFiveToMeet: string[];
}

export type GoldenGooseReportMode = 'top5' | 'full20';

export interface ReferralFrequency {
  profession: string;
  count: number;
}

// Computed by lib/goldenGoose/referralAnalysis.ts — pure application code,
// never generated by the model.
export interface ReferralAnalysisResult {
  totalReferrals: number;
  frequencies: ReferralFrequency[];
}

export interface PresentationResult {
  seconds: number;
  text: string;
}

export interface GoldenGooseSubmission {
  id: string;
  created_at: string;
  name: string;
  company_name: string;
  company_website: string;
  email: string;
  phone: string;
  role_description: string;
  role_clarification: RoleClarificationTurn[] | null;
  site_analysis: SiteAnalysis | null;
  verified_attributes: VerifiedAttributes | null;
  special_note: string | null;
  top5_report: GoldenGooseRow[] | null;
  full_report: GoldenGooseRow[] | null;
  referral_analysis: ReferralAnalysisResult | null;
  presentation_seconds: number | null;
  presentation_text: string | null;
  status: 'intake' | 'site_analyzed' | 'verified' | 'top5_done' | 'full_done' | 'presentation_done';
}
